# Generated by Django 5.2 on 2025-04-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('pose_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('benefits', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('channel_title', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='yoga.yogapose')),
            ],
        ),
    ]
